[package]
name = "untitled"
version = "0.1.0"
edition = "2024"


[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
pdfium = "0.9.5"

[[bin]]
name = "runner"
path = "src/main.rs"   # your local test executable
